### ISSUE TITLE
It seems that this plugin is no longer working.

### ISSUE THREAD

**Issue by sfu2008** [ozntel/oz-clear-unused-images-obsidian#39]
I haven’t used the cleanup feature for a while, but after testing it repeatedly recently, I found that it doesn’t seem to work anymore. Clicking the command doesn’t trigger any response.

**Comment by ozntel** [comment]
Not sure what you mean by there is no response. When I run the plugin, it looks like it works fine in the latest version of the Obsidian. If there is no file to delete, you will only see a notification that there is nothing to delete:

<img width="306" alt="image" src="https://github.com/user-attachments/assets/bd762a5d-b9c3-499c-b7a2-0467512773a5">

**Comment by aiyolo** [comment]
I also encounters the same problem, when I clicked clear unsed image, no notification pop up! my obsidian version is 1.6.7. on windows platform.

**Comment by sfu2008** [comment]
"I have found the issue. I had previously used a plugin called 'adv canvas'. This plugin adds its own code snippets to my canvas files, which causes the canvas files modified by this plugin to not open properly in OB when I’m not using it.

Because of this, the 'clear unused images' plugin couldn’t correctly parse these canvas files that couldn’t be opened, which is why it couldn’t delete them properly.

I have now fixed all the problematic canvas files, and the delete feature is working normally. I think the 'adv canvas' plugin is missing a feature, which is that when I disable or uninstall it, it should help me clean up the code snippets that OB can’t recognize."

**Comment by aiyolo** [comment]
For me, I didn't install the "advanced canvas" plugin, yet this plugin still doesn't work.

**Comment by 12ss22** [comment]
插件设置中排除包含.canvas的文件夹对我来说是有用的
